name: 'jMonkeyEngine Library'
description: 'Publish to jMonkeyEngine Library'
inputs:
  data: 
    description: 'JSON file containing entry data'
    required: false
  media-data-array: 
    description: 'JSON file containing an array of media data'
    required: false
  userId: 
    description: 'Library userId'
    required: true
  authId: 
    description: 'Library authId'
    required: true
  authKey: 
    description: 'Library authKey'
    required: true
  entryId: 
    description: 'ID of the entry (optional, by default the repo name is used)'
    required: false
  funding: 
    description: 'Enable funding for this entry'
    required: false        
  token:
    description: "Library token"
    required: true
  fetch-repo:
    description: 'Repo to fetch. Use "current" to specify the repo that launches the action'
    required: false
    default: "current"
  ref:
    description: 'Specify the ref to fetch. Default: default branch or current tag'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'